### ISSUE TITLE
 Illegal reflective access on JDK17

### ISSUE THREAD

**Issue by sdfelts** [eclipse-ee4j/glassfish-hk2#555]
Fatal error on JDK17, Warning on JDK11.

WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions
(file:/org.javassist.javassist.jar) to method
java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:159)
at javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:213)
at javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52)
at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
at javassist.ClassPool.toClass(ClassPool.java:1232)
at javassist.CtClass.toClass(CtClass.java:1384)
at org.glassfish.hk2.xml.internal.JAUtilities$Computer.compute(JAUtilities.java:242)

Javassist has been fixed for JDK11 but requires use of a new API.

I tested this fix in org/glassfish/hk2/xml/internal/JAUtilities.java

                  if(System.getProperty("java.version").startsWith("1.")) {
                    proxyClass = generated.toClass(key.getClassLoader(),
key.getProtectionDomain());
                  } else {
                    proxyClass = generated.toClass(key);
                  }

**Comment by jansupol** [comment]
A javassist of version at least 2.34 would be required. It comes with a new set of methods:

- `CtClass#toClass(Class)` which in turn calls 
- `ClassPool#toClass(CtClass, Class)`

Currently, `ClassPool#toClass(CtClass ct, Class<?> neighbor, ClassLoader loader, ProtectionDomain domain)` is called, and the javadoc to that method says:
> If your program is for only Java 9 or later, don't use this method. Use toClass(CtClass, Class) or toClass(CtClass, invoke.MethodHandles.Lookup).

Invoking the new (since 2.34) ` generated.toClass(key);` calls `ClassPool#toClass(CtClass ct, Class<?> neighbor)` which says:
> This method is available in Java 9 or later. It loads the class by using java.lang.invoke.MethodHandles with neighbor.

**Comment by jansupol** [comment]
Sorry I mean version [3.24](https://github.com/jboss-javassist/javassist/blob/rel_3_24_0_rc/src/main/javassist/CtClass.java#L1315).
